server {
    listen 443 ssl;
    server_name 10.30.235.3;
    ssl_certificate /var/www/mywebsite/flaskapp/ssl/signed_cert.pem;
    ssl_certificate_key /var/www/mywebsite/flaskapp/ssl/key.pem;
    client_max_body_size 1000M;
    location /api/ {
        proxy_pass http://127.0.0.1:5010/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        add_header X-Nginx-Proxy "true";
        proxy_connect_timeout 1000s;
        proxy_read_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_max_temp_file_size 0;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        keepalive_timeout 1000s;
    }
}
