<template>
  <div style="display: flex; min-height: 100vh; margin-top: 95px;">
    <!-- 左侧导航栏 -->
    <aside style="width: 280px; background-color: #f5f5f5; padding: 30px 20px;">
      <h3 style="font-weight: bold; font-size: 22px; margin-bottom: 24px;">Parameters</h3>
      <ul style="list-style: none; padding-left: 0;">
        <li @click="currentTab = 'parameter'" :style="{ cursor: 'pointer', color: currentTab === 'parameter' ? '#ff612c' : '#333', fontWeight: currentTab === 'parameter' ? '600' : 'normal', marginBottom: '10px', fontSize: '20px' }">▸ Parameter</li>
        <li @click="currentTab = 'adjustment'" :style="{ cursor: 'pointer', color: currentTab === 'adjustment' ? '#ff612c' : '#333', fontWeight: currentTab === 'adjustment' ? '600' : 'normal', fontSize: '20px' }">▸ Adjustment</li>
      </ul>
    </aside>

    <!-- 主体内容 -->
    <main style="flex-grow: 1; padding: 40px;">

      <!-- 面包屑导航 -->
      <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb-list">
          <li><svg style="width:16px; height:16px; fill:#666; vertical-align:middle;" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></svg> Home</li>
          <li>Parameter</li>
          <li>{{ currentTab === 'parameter' ? 'Parameter' : 'Adjustment' }}</li>
        </ol>
      </nav>

      <!-- Configuration Box with Progress Bar -->
      <div class="config-outer-box">
        <div class="progress-bar">
          <div class="progress-bar-inner" :style="{ width: uploadTried ? '100%' : '0%' }"></div>
        </div>
        <div class="config-inner-box">
          <h2 class="upload-title">{{ currentTab === 'parameter' ? 'Upload Parameter' : 'Upload Adjustment' }}</h2>
          <div style="display: flex; justify-content: center;">
            <div class="upload-box" :class="{ dragging: isDragging, 'has-file': selectedFile, success: uploadSuccess }" @dragover.prevent="onDragOver" @dragleave.prevent="onDragLeave" @drop.prevent="onDrop" @click="triggerFileInput">
              <input type="file" @change="handleFileChange" class="file-input" ref="fileInput" accept=".xlsx,.xls,.csv,.zip">
              <div class="upload-icon-text">
                <svg v-if="!selectedFile" width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M32 44V20M32 20L22 30M32 20L42 30" stroke="#B88A7A" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><rect x="12" y="44" width="40" height="8" rx="4" fill="#F8E6E3" stroke="#E9B8A7" stroke-width="2"/></svg>
                <p class="drop-text">{{ selectedFile ? selectedFile.name : 'Drop file or click here to browse' }}</p>
              </div>
              <p v-if="selectedFile" class="file-info">{{ formatFileSize(selectedFile.size) }}</p>
              <div v-if="selectedFile && autoGeneratedFilename" class="auto-filename-info" style="margin-top: 8px; padding: 8px; background-color: #e3f2fd; border-radius: 4px; font-size: 14px; color: #1976d2;">
                <strong>Auto-generated filename:</strong> {{ autoGeneratedFilename }}
              </div>
              <button v-if="selectedFile" @click.stop="uploadFile" class="upload-button">Upload File</button>
              <div v-if="message" class="message" :class="messageClass">{{ message }}</div>
            </div>
          </div>
          <!-- 版本名输入框，放在upload box下方 -->
          <div style="margin: 18px auto 0; max-width: 600px; display: flex; gap: 10px; justify-content: center;">
            <!-- Parameter Category Selection (only for Parameter tab) -->
            <select
              v-if="currentTab === 'parameter'"
              v-model="selectedCategory"
              class="version-control"
              style="width: 300px; min-width: 300px; height: 35px; padding: 0 15px; font-size: 15px;"
            >
              <option value="" disabled style="color: #888;">Select Parameter Category</option>
              <option v-for="category in parameterCategories" 
                      :key="category" 
                      :value="category"
                      style="padding: 10px 0;"
              >
                {{ category }}
              </option>
            </select>
            <input
              v-model="versionSuffix"
              :placeholder="currentTab === 'parameter' ? 'Enter parameter version name' : 'Enter adjustment version name'"
              class="version-control"
              :style="currentTab === 'parameter' ? 'width: 300px; min-width: 300px; height: 35px; padding: 0 15px; font-size: 15px;' : 'width: 600px; min-width: 600px; height: 35px; padding: 0 15px; font-size: 15px;'"
            />
          </div>
          <!-- Instructions box -->
          <div class="instructions-box no-bg" style="margin-top: 0px;">
            <p class="instructions-title">Instructions:</p>
            <ul class="instructions-list">
              <li>1. Select category from the dropdown list (optional).</li>
              <li>2. Enter the version name (If not entered, will use timestamp as default).</li>
              <li>3. Select and upload your file.</li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Review Box -->
      <div style="margin-top: 50px;">
        <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 0;">Review</h2>
        <div style="margin-bottom: 10px; padding: 8px; background-color: #e3f2fd; border-radius: 4px; font-size: 14px; color: #1976d2;">
          <strong>Note:</strong> Only records that have passed pre-run validation can be approved. 
          Records with ✓ are eligible for approval, records with ⚠ need pre-run validation first.
        </div>
        <div style="max-height: 640px; overflow-y: auto; border: 1px solid #e0e0e0; border-radius: 4px; background: white; min-width: 1200px;">

          <table style="width: 100%; border-collapse: collapse; background: white;">
            <thead style="background: #f7f7f7; position: sticky; top: 0; z-index: 1;">
              <tr>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 10px;">
                  <input 
                    type="checkbox" 
                    v-model="allSelected" 
                    :disabled="!hasEligibleRecords"
                    :title="hasEligibleRecords ? 'Select all eligible records' : 'No records eligible for approval'"
                  >
                </th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 100px;">Maker</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 140px;">Time</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 70px;">Type</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 70px;">Category</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 140px;">Action</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 50px;">Status</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 100px;">Checker</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 40px;">Download File</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 40px;">Pre-run Validation</th>
              </tr>
            </thead>
            <tbody>
              <template v-for="(item, index) in reviewList" :key="index">
                <tr :style="{ 
                  backgroundColor: item.approved ? '#e8f5e9' : item.hasPassedPreRunValidation ? '#f0f8ff' : '#f5f5f5',
                  opacity: item.hasPassedPreRunValidation ? 1 : 0.7
                }">
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">
                    <input 
                      type="checkbox" 
                      v-model="item.selected" 
                      :disabled="!item.hasPassedPreRunValidation"
                      :title="item.hasPassedPreRunValidation ? 'Can be approved' : 'Must pass pre-run validation first'"
                    >
                  </td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.maker }}</td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.time }}</td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.type }}</td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.category || '-' }}</td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.action }}</td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">
                    <span :style="{ 
                      color: item.hasPassedPreRunValidation ? '#4caf50' : '#ff9800',
                      fontWeight: 'bold'
                    }">
                      {{ item.status }}
                      <span v-if="item.hasPassedPreRunValidation" style="margin-left: 5px;">✓</span>
                      <span v-else style="margin-left: 5px;">⚠</span>
                    </span>
                  </td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.checker }}</td>
                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;"><button @click="downloadRow(index)" :style="{ color: item.downloaded ? '#4CAF50' : '#333', cursor: 'pointer', fontSize: '20px', background: 'none', border: 'none' }">⬇️</button></td>
                                  <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">
                  <button 
                    @click="startPreRunValidation(item, index)"
                    :disabled="item.preRunValidation?.status === 'running'"
                    :style="{ 
                      color: '#333',
                      cursor: item.preRunValidation?.status === 'running' ? 'not-allowed' : 'pointer',
                      fontSize: '20px',
                      background: 'none',
                      border: 'none'
                    }"
                  >
                    ▶️
                  </button>
                </td>
                </tr>
              </template>
            </tbody>
          </table>
        </div>
        <div style="margin-top: 3px; text-align: right;">
          <button 
            class="upload-button" 
            style="background: #FF612C;" 
            @click="approveSelected"
            :disabled="!hasSelectedEligibleRecords"
            :title="hasSelectedEligibleRecords ? 'Approve selected records' : 'No eligible records selected'"
          >
            Approve
          </button>
        </div>
      </div>

      <!-- Pre-run Validation Records Table -->
      <div style="margin-top: 50px;">
        <h2 style="font-size: 20px; font-weight: 600; margin-bottom: 0;">Pre-run Validation Records</h2>
        <div style="max-height: 640px; overflow-y: auto; border: 1px solid #e0e0e0; border-radius: 4px; background: white; min-width: 1200px;">

          <table style="width: 100%; border-collapse: collapse; background: white;">
            <thead style="background: #f7f7f7; position: sticky; top: 0; z-index: 1;">
              <tr>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 100px;">Maker</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 160px;">Time</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 80px;">Type</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 80px;">Category</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 120px;">Action</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 100px;">Status</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 40px;">Download Log</th>
                <th style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center; min-width: 40px;">Download Report</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in prerunValidationList" :key="item.id" :style="{ backgroundColor: '#fff' }">
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.maker }}</td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.time }}</td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.type }}</td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.category || '-' }}</td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.action }}</td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">{{ item.status }}</td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">
                  <button 
                    @click="downloadValidationLogs(item.task_id)"
                    :style="{ 
                      color: '#333',
                      cursor: 'pointer',
                      fontSize: '20px',
                      background: 'none',
                      border: 'none'
                    }"
                  >
                    ⬇️
                  </button>
                </td>
                <td style="text-align: center; padding: 12px; border-bottom: 1px solid #e0e0e0;">
                  <button 
                    @click="downloadValidationReport(item.task_id)"
                    :disabled="item.status !== 'Completed'"
                    :style="{ 
                      color: '#333',
                      cursor: item.status === 'Completed' ? 'pointer' : 'not-allowed',
                      fontSize: '20px',
                      background: 'none',
                      border: 'none'
                    }"
                  >
                    ⬇️
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import axios from 'axios'
import { getUserDisplayName } from '../services/authService'

const currentTab = ref<'parameter' | 'adjustment'>('parameter')
const selectedFile = ref<File | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)
const message = ref('')
const isDragging = ref(false)
const uploadSuccess = ref(false)
const uploadTried = ref(false)

// Suffix
const versionSuffix = ref('')
// Current timestamp
const currentTimestamp = ref('')

// Unified review list from database
const reviewList = ref<any[]>([])
// Pre-run validation records list
const prerunValidationList = ref<any[]>([])

const messageClass = computed(() => message.value.includes('✅') ? 'success' : message.value.includes('❌') ? 'error' : 'info')

const allSelected = computed({
  get: () => {
    const eligibleItems = reviewList.value.filter(item => item.hasPassedPreRunValidation)
    return eligibleItems.length > 0 && eligibleItems.every(item => item.selected)
  },
  set: (val: boolean) => {
    // Only select items that have passed pre-run validation
    reviewList.value.forEach(item => {
      if (item.hasPassedPreRunValidation) {
        item.selected = val
      }
    })
  }
})

// Check if there are any records eligible for approval
const hasEligibleRecords = computed(() => {
  return reviewList.value.some(item => item.hasPassedPreRunValidation)
})

// Check if there are any selected records that are eligible for approval
const hasSelectedEligibleRecords = computed(() => {
  return reviewList.value.some(item => item.selected && item.hasPassedPreRunValidation)
})

const selectedCategory = ref('')
const parameterCategories = ['Regular', 'Non-regular']

// Auto-generated filename based on tab and category
const autoGeneratedFilename = computed(() => {
  if (currentTab.value === 'parameter') {
    if (selectedCategory.value === 'Regular') {
      return 'CNCBI ECL engine param table_regular updated.xlsx'
    } else if (selectedCategory.value === 'Non-regular') {
      return 'CNCBI ECL engine param table_not regularly updated.xlsx'
    }
  } else if (currentTab.value === 'adjustment') {
    return 'CNCBI ECL engine param table_adjustment data.xlsx'
  }
  return ''
})

// Generate current timestamp
const generateTimestamp = () => {
  const now = new Date()
  const pad = (n: number) => n.toString().padStart(2, '0')
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`
}

// Watch for tab changes and clear upload box
watch(currentTab, () => {
  selectedFile.value = null
  message.value = ''
  uploadSuccess.value = false
  uploadTried.value = false
  if (fileInput.value) fileInput.value.value = ''
  // 切换tab时清空versionSuffix和selectedCategory
  versionSuffix.value = ''
  selectedCategory.value = ''
  // 更新时间戳
  currentTimestamp.value = generateTimestamp()
})

// Load data from database
const loadReviewRecords = async () => {
  try {
    const response = await axios.get('/api/get_review_records')
    reviewList.value = response.data.records.map((record: any) => ({
      ...record,
      approved: record.status === 'Approved',
      downloaded: false,
      selected: false,
      preRunValidation: null // Initialize preRunValidation field
    }))
    
    // Load pre-run validation records for each parameter/adjustment
    await loadPreRunValidationRecords()
  } catch (error) {
    console.error('Error loading review records:', error)
  }
}

// Load pre-run validation records from database
const loadPreRunValidationRecords = async () => {
  try {
    const response = await axios.get('/api/get_prerun_validation_records')
    prerunValidationList.value = (response.data.records || []).map((record: any) => ({
      ...record,
      type: record.upload_type || record.type, // Use upload_type if available, otherwise fallback to type
      action: `Pre-run Validation: ${(record.upload_type || record.type) === 'Parameter' ? 'par' : 'adj'}_${record.upload_timestamp || record.timestamp}`
    }))
    
    // Update reviewList with pre-run validation status
    updateReviewListWithValidationStatus()
  } catch (error) {
    console.error('Error loading pre-run validation records:', error)
    prerunValidationList.value = []
  }
}

// Check if a record has passed pre-run validation
const hasPassedPreRunValidation = (reviewRecord: any) => {
  // Find matching pre-run validation record
  const validationRecord = prerunValidationList.value.find(validation => {
    // Match by upload_timestamp and upload_type
    const matchesTimestamp = validation.upload_timestamp === reviewRecord.timestamp
    const matchesType = validation.upload_type === reviewRecord.type
    return matchesTimestamp && matchesType
  })
  
  // Return true if validation record exists and status is 'Completed'
  return validationRecord && validationRecord.status === 'Completed'
}

// Update review list with pre-run validation status
const updateReviewListWithValidationStatus = () => {
  reviewList.value.forEach(record => {
    record.hasPassedPreRunValidation = hasPassedPreRunValidation(record)
  })
}

// Load data when component mounts
onMounted(() => {
  loadReviewRecords()
  // 初始化时间戳
  currentTimestamp.value = generateTimestamp()
})

const triggerFileInput = (e: Event) => {
  if ((e.target as HTMLElement).classList.contains('upload-button')) return
  fileInput.value?.click()
}

const handleFileChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  if (target.files?.[0]) {
    selectedFile.value = target.files[0]
    message.value = ''
    uploadSuccess.value = false
  }
}

const onDragOver = () => isDragging.value = true
const onDragLeave = () => isDragging.value = false
const onDrop = (e: DragEvent) => {
  isDragging.value = false
  if (e.dataTransfer?.files?.length) {
    selectedFile.value = e.dataTransfer.files[0]
    message.value = ''
    uploadSuccess.value = false
  }
}

const formatFileSize = (bytes: number): string => {
  if (bytes < 1024) return bytes + ' bytes'
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB'
  return (bytes / 1048576).toFixed(1) + ' MB'
}

const uploadFile = async () => {
  if (!selectedFile.value) return

  const formData = new FormData()
  formData.append('file', selectedFile.value)
  formData.append('fileType', currentTab.value === 'parameter' ? 'parameter' : 'adjustment')
  formData.append('suffix', versionSuffix.value.trim())
  formData.append('category', selectedCategory.value)
  formData.append('auto_filename', autoGeneratedFilename.value)
  formData.append('maker', getUserDisplayName())

  try {
    message.value = '⏳ Uploading...'
    const response = await axios.post('/api/upload', formData, {
      headers: { 'Content-Type': 'multipart/form-data' }
    })
    message.value = '✅ ' + response.data.message
    uploadSuccess.value = true
    fileInput.value!.value = ''
    uploadTried.value = true

    await loadReviewRecords()
    selectedFile.value = null
  } catch (error: any) {
    message.value = '❌ ' + (error.response?.data?.error || 'Upload failed.')
    uploadSuccess.value = false
    uploadTried.value = true
  }
}

const downloadRow = async (index: number) => {
  const item = reviewList.value[index]
  try {
    // Call the download API
    const response = await axios.get(`/api/download_files/${item.id}`, {
      responseType: 'blob'
    })
    
    // Create download link
    const url = window.URL.createObjectURL(new Blob([response.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `${item.action.replace('upload: ', '')}.zip`)
    document.body.appendChild(link)
    link.click()
    link.remove()
    window.URL.revokeObjectURL(url)
    
    item.downloaded = true
  } catch (error) {
    console.error('Download failed:', error)
    alert('Download failed. Please try again.')
  }
}

const approveSelected = async () => {
  try {
    // Only process items that are selected AND have passed pre-run validation
    const selectedItems = reviewList.value.filter(item => item.selected && item.hasPassedPreRunValidation)
    
    if (selectedItems.length === 0) {
      alert('No eligible records selected for approval. Records must pass pre-run validation first.')
      return
    }
    
    for (const item of selectedItems) {
      // Call API to update approval status
      await axios.post('/api/update_approval_status', {
        id: item.id,
        status: 'Approved',
        checker: getUserDisplayName()
      })
    }
    
    // Refresh the review list from database
    await loadReviewRecords()
    
  } catch (error) {
    console.error('Approval failed:', error)
    alert('Approval failed. Please try again.')
  }
}

// Pre-run Validation functions
const startPreRunValidation = async (item: any, index: number) => {
  try {
    // Determine if this is a parameter or adjustment
    const isParameter = item.type === 'Parameter'
    const folderName = isParameter ? 
      `par_${item.timestamp}${item.category ? '_' + item.category : ''}${item.suffix ? '_' + item.suffix : ''}` :
      `adj_${item.timestamp}${item.category ? '_' + item.category : ''}${item.suffix ? '_' + item.suffix : ''}`
    
    // Generate UI timestamp
    const now = new Date()
    const pad = (n: number) => n.toString().padStart(2, '0')
    const uiTimestamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`
    
    // Start validation
    const response = await axios.post('/api/start_prerun_validation', {
      parameterFolder: isParameter ? folderName : '',
      adjustmentFolder: !isParameter ? folderName : '',
      maker: getUserDisplayName(),  // Use current logged-in user as maker
      ui_timestamp: uiTimestamp,
      upload_timestamp: item.timestamp,  // Pass the original upload timestamp
      upload_type: item.type  // Pass the upload type (Parameter/Adjustment)
    })
    
    // Update the item with validation info
    item.preRunValidation = {
      taskId: response.data.task_id,
      status: 'running',
      timestamp: response.data.timestamp
    }
    
    // Update the checker in the upload table to current user
    item.checker = getUserDisplayName()
    
    // Update the database record to reflect the checker change
    await axios.post('/api/update_approval_status', {
      id: item.id,
      status: item.status,
      checker: getUserDisplayName()
    })
    
    // Refresh pre-run validation list
    await loadPreRunValidationRecords()
    
    // Start polling for status updates
    pollValidationStatus(response.data.task_id, index)
    
  } catch (error: any) {
    console.error('Failed to start pre-run validation:', error)
    alert(error.response?.data?.error || 'Failed to start validation. Please try again.')
  }
}

const pollValidationStatus = async (taskId: string, index: number) => {
  try {
    const response = await axios.get(`/api/prerun_validation_status/${taskId}`)
    const status = response.data.status
    
    // Update the item status
    if (reviewList.value[index] && reviewList.value[index].preRunValidation) {
      reviewList.value[index].preRunValidation.status = status
    }
    
    // Refresh pre-run validation list
    await loadPreRunValidationRecords()
    
    // Continue polling if still running
    if (status === 'running') {
      setTimeout(() => pollValidationStatus(taskId, index), 5000) // Poll every 5 seconds
    } else {
      // If validation is completed or failed, update the validation status for all records
      updateReviewListWithValidationStatus()
    }
    
  } catch (error) {
    console.error('Error polling validation status:', error)
    // Update status to failed if polling fails
    if (reviewList.value[index] && reviewList.value[index].preRunValidation) {
      reviewList.value[index].preRunValidation.status = 'failed'
    }
  }
}

const downloadValidationLogs = async (taskId: string) => {
  try {
    const response = await axios.get(`/api/download_prerun_validation_logs/${taskId}`, {
      responseType: 'blob'
    })
    
    // Create download link
    const url = window.URL.createObjectURL(new Blob([response.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `prerun_validation_logs_${taskId}.zip`)
    document.body.appendChild(link)
    link.click()
    link.remove()
    window.URL.revokeObjectURL(url)
    
  } catch (error) {
    console.error('Download validation logs failed:', error)
    alert('Download failed. Please try again.')
  }
}

const downloadValidationReport = async (taskId: string) => {
  try {
    const response = await axios.get(`/api/download_prerun_validation_report/${taskId}`, {
      responseType: 'blob'
    })
    
    // Create download link
    const url = window.URL.createObjectURL(new Blob([response.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `prerun_validation_report_${taskId}.zip`)
    document.body.appendChild(link)
    link.click()
    link.remove()
    window.URL.revokeObjectURL(url)
    
  } catch (error) {
    console.error('Download validation report failed:', error)
    alert('Download failed. Please try again.')
  }
}
</script>

<style scoped>
.upload-box {
  width: 400px;
  height: 220px;
  border: 2px dashed #E9B8A7;
  padding: 0 24px;
  text-align: center;
  border-radius: 16px;
  background: #F8E6E3;
  transition: all 0.3s ease;
  cursor: pointer;
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  margin: 0 auto;
}
.upload-icon-text {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.upload-box.dragging {
  border-color: #ff612c;
  background: #fff1ee;
  transform: scale(1.01);
}
.upload-box.success {
  border-color: #4CAF50;
  background: #e8f5e9;
}
.upload-box.success:hover {
  border-color: #4CAF50;
  background: #e8f5e9;
}
.upload-box:hover {
  border-color: #ff612c;
  background-color: #fff1ee;
}
.file-input { display: none; }
.drop-text {
  font-size: 16px;
  color: #888;
  margin: 0;
  max-width: 90%;
  word-break: break-word;
}
.file-info {
  margin: 5px 0 15px;
  font-size: 14px;
  color: #555;
}
.upload-button {
  padding: 12px 24px;
  background: #4CAF50;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 16px;
  transition: all 0.3s;
  margin-top: 15px;
}
.upload-button:hover {
  background: #45a049;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0,0,0,0.1);
}
.message {
  margin-top: 20px;
  padding: 15px;
  border-radius: 6px;
  font-size: 14px;
  width: 100%;
  box-sizing: border-box;
}
.message.info { background-color: #e3f2fd; color: #0d47a1; }
.message.success { background-color: #e8f5e9; color: #2e7d32; }
.message.error { background-color: #ffebee; color: #c62828; }
.breadcrumb-nav {
  margin-bottom: 18px;
}
.breadcrumb-list {
  display: flex;
  align-items: center;
  gap: 8px;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 18px;
  color: #555;
}
.breadcrumb-list li:not(:last-child)::after {
  content: '>';
  margin: 0 6px;
  color: #bbb;
}
.config-outer-box {
  background: #fff;
  border-radius: 10px;
  box-shadow: 0 2px 12px rgba(21,61,119,0.06);
  padding: 0 0 16px 0;
  margin-bottom: 30px;
  position: relative;
}
.config-inner-box {
  padding: 20px 30px 0 30px;
}
.upload-title {
  font-size: 20px;
  font-weight: bold;
  color: #153D77;
  margin-bottom: 20px;
}
.progress-bar {
  height: 5px;
  background: #e3e8f0;
  border-radius: 10px 10px 0 0;
  overflow: hidden;
}
.progress-bar-inner {
  height: 100%;
  background: #153D77;
  transition: width 0.4s cubic-bezier(.4,2,.6,1);
}
.version-input-large, .version-input-beauty {
  display: none;
}
.version-control {
  width: 100%;
  max-width: 340px;
  font-size: 15px;
  height: 30px;
  font-weight: 500;
  border: 1.2px solid #e0e0e0;
  border-radius: 10px;
  padding: 10px 16px;
  box-sizing: border-box;
  margin-bottom: 0;
  background: #fff;
  box-shadow: 0 1px 6px rgba(21,61,119,0.05);
  outline: none;
  transition: border-color 0.2s, box-shadow 0.2s;
}
.version-control:focus {
  border-color: #ff612c;
  box-shadow: 0 2px 8px rgba(255,97,44,0.08);
}
.version-control::placeholder {
  color: #bbb;
  font-size: 16px;
  font-weight: 400;
  letter-spacing: 0.5px;
}
.instructions-box {
  margin-top: 30px;
  background: none;
  padding: 0 10px 0 0;
}
.instructions-title {
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 6px;
  color: #153D77;
}
.instructions-list {
  font-size: 16px;
  color: #666;
  line-height: 1.3;
  margin: 0;
  padding-left: 18px;
}
.instructions-list li {
  margin-bottom: 3px;
}


</style>